#!/bin/bash

#       Copyright (c) Stratus Technologies Bermuda Ltd., 2008.
#       All Rights Reserved. Unpublished rights reserved
#       under the copyright laws of the United States.
# 
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU Lesser General Public License as published
#       by the Free Software Foundation; version 2.1 only. with the special
#       exception on linking described in file LICENSE.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU Lesser General Public License for more details.

#
#   stub
#   ha_propose_master
#

. /usr/libexec/xapi/cluster-stack/xhad/ha_stubrc

get_xhad_status
    sf=$_sf
    localhost=$_localhost
    cf=$_cf

# read the pool state
readglobal $sf
    state=$_state
    host0=$_host0
    host1=$_host1
    master=$_master

if [ $state != "active" ]; then
    error "Invalid pool state" 1
fi

(writeglobal $sf $state $host0 $host1 $localhost) || exit $?

echo TRUE
exit 0
