#!/bin/bash

#       Copyright (c) Stratus Technologies Bermuda Ltd., 2008.
#       All Rights Reserved. Unpublished rights reserved
#       under the copyright laws of the United States.
# 
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU Lesser General Public License as published
#       by the Free Software Foundation; version 2.1 only. with the special
#       exception on linking described in file LICENSE.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU Lesser General Public License for more details.

#
#   stub
#   ha_stop_daemon
#

. /usr/libexec/xapi/cluster-stack/xhad/ha_stubrc

get_xhad_status
    sf=$_sf
    localhost=$_localhost
    cf=$_cf

# set host state to offline
gethostlist $cf     # sets host0 and host1
    localhost=$_localhost
    localhost_index=$_localhost_index

(writespecific $sf $localhost_index offline $localhost) || exit $?

remove_xhad_status

exit 0
