#!/bin/bash

#       Copyright (c) Stratus Technologies Bermuda Ltd., 2008.
#       All Rights Reserved. Unpublished rights reserved
#       under the copyright laws of the United States.
# 
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU Lesser General Public License as published
#       by the Free Software Foundation; version 2.1 only. with the special
#       exception on linking described in file LICENSE.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU Lesser General Public License for more details.

#
#   stub
#   ha_set_pool_state    init | active | invalid [-C <config-file-name>]
#

. /opt/xensource/xha/ha_stubrc

#   Get new state
newstate=`param $*` || exit $?
shift

# get config-file name
cf=`getcf $*` || exit $?

# get state-file name from the config-file
sf=`getsf $cf` || exit $?

case $newstate in
    init)
        # write new state to the state-file
        
        # initialize global section
        gethostlist $cf     # sets host0 and host1
            host0=$_host0
            host1=$_host1
        (writeglobal $sf $newstate $host0 $host1 NULL) || exit $?

        # intiialize host-specific section
        (writespecific $sf 0 offline NULL) || exit $?
        (writespecific $sf 1 offline NULL) || exit $?
        ;;
    active)
        ;;
    invalid)
        (echo $newstate) > $sf || exit $?
        ;;
    *)
        error "Invalid new state $newstate" 1
        ;;
esac

exit 0
