#!/bin/bash

#       Copyright (c) Stratus Technologies Bermuda Ltd., 2008.
#       All Rights Reserved. Unpublished rights reserved
#       under the copyright laws of the United States.
# 
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU Lesser General Public License as published
#       by the Free Software Foundation; version 2.1 only. with the special
#       exception on linking described in file LICENSE.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU Lesser General Public License for more details.

#
#   stub
#   ha_start_daemon [-C <config-file-name>]
#

. /opt/xensource/xha/ha_stubrc

# get config-file name
cf=`getcf $*` || exit $?

# get state-file name from the config-file
sf=`getsf $cf` || exit $?

# read the pool state
readglobal $sf
    state=$_state
    host0=$_host0
    host1=$_host1
    master=$_master

gethostlist $cf
    localhost=$_localhost
    localhost_index=$_localhost_index

case $state in
    init)
        (writeglobal $sf active $host0 $host1 NULL) || exit $?
        (writespecific $sf $localhost_index online $localhost) || exit $?
        ;;
    active)
        (writespecific $sf $localhost_index online $localhost) || exit $?
        ;;
    *)
        error "Invalid pool state for ha_start_daemon - $state" 1
        ;;
esac

set_xhad_status $sf $localhost $cf

exit 0
