//
//      Copyright (c) Stratus Technologies Bermuda Ltd., 2008.
//      All Rights Reserved. Unpublished rights reserved
//      under the copyright laws of the United States.
//
//      This program is free software; you can redistribute it and/or modify
//      it under the terms of the GNU Lesser General Public License as published
//      by the Free Software Foundation; version 2.1 only. with the special
//      exception on linking described in file LICENSE.
//
//      This program is distributed in the hope that it will be useful,
//      but WITHOUT ANY WARRANTY; without even the implied warranty of
//      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//      GNU Lesser General Public License for more details.
//
//
//  DESCRIPTION:
//
//      This module reads and writes when HA daemon is not present.
//
//  AUTHORS:
//
//      Satoshi Watanabe
//
//  CREATION DATE: 
//
//      March 24, 2008
//
//   

//
//
//  O P E R A T I N G   S Y S T E M   I N C L U D E   F I L E S
//
//

#define _GNU_SOURCE
#include <stdio.h>
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>


//
//
//  M A R A T H O N   I N C L U D E   F I L E S
//
//

#include "mtctypes.h"
#define MTC_NEED_ERROR_TABLE
#include "mtcerrno.h"

int
main()
{
    int index;


    printf("#!/bin/bash\n");
    printf("#CAUTION:\n");
    printf("#\tDo not edit this file manually.\n");
    printf("#\tThis file is generated by ./generr\n");
    printf("\n");

    for (index = 0; index < sizeof(mtc_errtable) / sizeof(mtc_errtable[0]); index++)
    {
        if (mtc_errtable[index].name)
        {
            printf("%s=%d\n", mtc_errtable[index].name, mtc_errtable[index].status);
        }
    }

    return 0;
}
